INSERT INTO `individualprojectstickalster`.`kategori` (`namn`) VALUES ('sjal');
INSERT INTO `individualprojectstickalster`.`kategori` (`namn`) VALUES ('mössa');
INSERT INTO `individualprojectstickalster`.`kategori` (`namn`) VALUES ('vantar');
INSERT INTO `individualprojectstickalster`.`kategori` (`namn`) VALUES ('halsduk');
INSERT INTO `individualprojectstickalster`.`kategori` (`namn`) VALUES ('sockar');
INSERT INTO `individualprojectstickalster`.`kategori` (`namn`) VALUES ('klänning');
INSERT INTO `individualprojectstickalster`.`kategori` (`namn`) VALUES ('slipover');
INSERT INTO `individualprojectstickalster`.`kategori` (`namn`) VALUES ('påse');
INSERT INTO `individualprojectstickalster`.`kategori` (`namn`) VALUES ('tofflor');